### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by FernandoHCFaria** [GreenMeteor/adsense#15]
Is it possible to create the string for those phrases?

![image](https://github.com/user-attachments/assets/c5f6c462-6203-4695-81e3-7d8ae85f519f)

**Comment by ArchBlood** [comment]
It's possible by making them translatable by replacing the plain text with the following;

```php
<?= Yii::t('AdsenseModule.base', '<b>AdBlocker Detected</b>'); ?>
``` 
and
```php
<?= Yii::t('AdsenseModule.base', 'Please disable AdBlocker to view content.'); ?>
```
