### ISSUE TITLE
ads.txt

### ISSUE THREAD

**Issue by wehowski** [GreenMeteor/adsense#4]
Helllo,
I am new to humhub and this module, please excuse if my question was answered before already anywhere?

As I know, it is nessecary to serve an ads,txt file to get the revenue for google.
I think I have to add this for myself, or does the module provide the ads.txt anyway?

Thank you!

**Comment by ArchBlood** [comment]
Hello, and thank you for creating an issue, to answer your question, this module does not provide any such file, it is up to the site owner to create an `ads.txt` file, I've attached the link to the Ads.txt guide by Google itself.

https://support.google.com/adsense/answer/7532444?hl=en

**Comment by ArchBlood** [comment]
In an upcoming version of the AdSense module we will have a new function added for creating, overwriting and appending a Ads.txt file as well as better tracking of AdBlockers!

![Screenshot_1](https://github.com/user-attachments/assets/d59fa408-ff60-4713-9e47-e466ae82509f)
