### ISSUE TITLE
Remove adsense from Humhub directory page

### ISSUE THREAD

**Issue by Timmer2021** [GreenMeteor/adsense#7]
Hello.

To meet Google Adsenses policy, I need to be able to remove the ads on pages that are without content or with low value content, that are used for alerts, navigation or other behavioral purposes. I believe I'm being flagged for the directory page which has an ad slot, but no content to satisfy Google's policy..

Is there any easy way to edit that particular page to remove the ad block?

Thanks in aadvance.
Tim.

**Comment by ArchBlood** [comment]
In older releases, I can not really do much, but soon it will be completely removed for 1.9+ of HumHub;

Closed by https://github.com/GreenMeteor/adsense/commit/7b4587e14a056fa462ea288893716c6e4a0b9b12
